-- DotJob 数据库初始化脚本
-- 适用于 MySQL 数据库
-- ============================================
-- 1. 用户表 (JOB_USER)
-- ============================================
CREATE TABLE IF NOT EXISTS `JOB_USER` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    `USERNAME` VARCHAR(50) NOT NULL COMMENT '用户名',
    `PASSWORD` VARCHAR(256) NOT NULL COMMENT '密码(已加密)',
    `DISPLAY_NAME` VARCHAR(100) NULL COMMENT '显示名称',
    `EMAIL` VARCHAR(100) NULL COMMENT '邮箱',
    `IS_ENABLED` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `LAST_LOGIN_AT` DATETIME NULL COMMENT '最后登录时间',
    `ROLE` VARCHAR(20) NOT NULL DEFAULT 'User' COMMENT '角色: Admin, User',
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `IX_JOB_USER_USERNAME` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- ============================================
-- 2. 日志表 (JOB_LOG)
-- ============================================
CREATE TABLE IF NOT EXISTS `JOB_LOG` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '日志ID',
    `BEGIN_TIME` DATETIME NOT NULL COMMENT '开始时间',
    `END_TIME` DATETIME NOT NULL COMMENT '结束时间',
    `JOB_NAME` VARCHAR(200) NULL COMMENT '任务名称(格式: Group.Name)',
    `JOB_GROUP` VARCHAR(100) NULL COMMENT '任务分组',
    `ERROR_MSG` TEXT NULL COMMENT '错误信息',
    `EXECUTE_TIME` DOUBLE NOT NULL DEFAULT 0 COMMENT '执行耗时(秒)',
    `PARAMETERS` TEXT NULL COMMENT '请求参数',
    `URL` VARCHAR(500) NULL COMMENT '请求URL',
    `REQUEST_TYPE` VARCHAR(20) NULL COMMENT '请求类型',
    `RESULT` TEXT NULL COMMENT '返回结果',
    `STATUS_CODE` INT NULL COMMENT 'HTTP状态码',
    `EXECUTION_STATUS` INT NOT NULL DEFAULT 0 COMMENT '执行状态: 0-进行中, 1-成功, 2-失败',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    INDEX `IX_JOB_LOG_JOB_NAME` (`JOB_NAME`),
    INDEX `IX_JOB_LOG_BEGIN_TIME` (`BEGIN_TIME`),
    INDEX `IX_JOB_LOG_EXECUTION_STATUS` (`EXECUTION_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务执行日志表';

-- ============================================
-- 3. Quartz.NET 相关表 (如果不存在)
-- ============================================
-- 注意: 以下是 Quartz.NET 所需的表结构
-- 如果您使用 Quartz.NET 的自动建表功能，可以跳过这部分

-- QRTZ_JOB_DETAILS 表
CREATE TABLE IF NOT EXISTS `QRTZ_JOB_DETAILS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `JOB_NAME` VARCHAR(200) NOT NULL,
    `JOB_GROUP` VARCHAR(200) NOT NULL,
    `DESCRIPTION` VARCHAR(250) NULL,
    `JOB_CLASS_NAME` VARCHAR(250) NOT NULL,
    `IS_DURABLE` TINYINT(1) NOT NULL,
    `IS_NONCONCURRENT` TINYINT(1) NOT NULL,
    `IS_UPDATE_DATA` TINYINT(1) NOT NULL,
    `REQUESTS_RECOVERY` TINYINT(1) NOT NULL,
    `JOB_DATA` BLOB NULL,
    PRIMARY KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_TRIGGERS 表
CREATE TABLE IF NOT EXISTS `QRTZ_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(200) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(200) NOT NULL,
    `JOB_NAME` VARCHAR(200) NOT NULL,
    `JOB_GROUP` VARCHAR(200) NOT NULL,
    `DESCRIPTION` VARCHAR(250) NULL,
    `NEXT_FIRE_TIME` BIGINT NULL,
    `PREV_FIRE_TIME` BIGINT NULL,
    `PRIORITY` INT NULL,
    `TRIGGER_STATE` VARCHAR(16) NOT NULL,
    `TRIGGER_TYPE` VARCHAR(8) NOT NULL,
    `START_TIME` BIGINT NOT NULL,
    `END_TIME` BIGINT NULL,
    `CALENDAR_NAME` VARCHAR(200) NULL,
    `MISFIRE_INSTR` SMALLINT NULL,
    `JOB_DATA` BLOB NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    INDEX `IDX_QRTZ_T_J` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
    INDEX `IDX_QRTZ_T_JG` (`SCHED_NAME`, `JOB_GROUP`),
    INDEX `IDX_QRTZ_T_C` (`SCHED_NAME`, `CALENDAR_NAME`),
    INDEX `IDX_QRTZ_T_G` (`SCHED_NAME`, `TRIGGER_GROUP`),
    INDEX `IDX_QRTZ_T_STATE` (`SCHED_NAME`, `TRIGGER_STATE`),
    INDEX `IDX_QRTZ_T_N_STATE` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`, `TRIGGER_STATE`),
    INDEX `IDX_QRTZ_T_N_G_STATE` (`SCHED_NAME`, `TRIGGER_GROUP`, `TRIGGER_STATE`),
    INDEX `IDX_QRTZ_T_NEXT_FIRE_TIME` (`SCHED_NAME`, `NEXT_FIRE_TIME`),
    INDEX `IDX_QRTZ_T_NFT_ST` (`SCHED_NAME`, `TRIGGER_STATE`, `NEXT_FIRE_TIME`),
    INDEX `IDX_QRTZ_T_NFT_MISFIRE` (`SCHED_NAME`, `MISFIRE_INSTR`, `NEXT_FIRE_TIME`),
    INDEX `IDX_QRTZ_T_NFT_ST_MISFIRE` (`SCHED_NAME`, `MISFIRE_INSTR`, `NEXT_FIRE_TIME`, `TRIGGER_STATE`),
    INDEX `IDX_QRTZ_T_NFT_ST_MISFIRE_GRP` (`SCHED_NAME`, `MISFIRE_INSTR`, `NEXT_FIRE_TIME`, `TRIGGER_GROUP`, `TRIGGER_STATE`),
    CONSTRAINT `FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS` FOREIGN KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`)
        REFERENCES `QRTZ_JOB_DETAILS` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_SIMPLE_TRIGGERS 表
CREATE TABLE IF NOT EXISTS `QRTZ_SIMPLE_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(200) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(200) NOT NULL,
    `REPEAT_COUNT` BIGINT NOT NULL,
    `REPEAT_INTERVAL` BIGINT NOT NULL,
    `TIMES_TRIGGERED` BIGINT NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    CONSTRAINT `FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
        REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_CRON_TRIGGERS 表
CREATE TABLE IF NOT EXISTS `QRTZ_CRON_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(200) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(200) NOT NULL,
    `CRON_EXPRESSION` VARCHAR(120) NOT NULL,
    `TIME_ZONE_ID` VARCHAR(80) NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    CONSTRAINT `FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
        REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_SIMPROP_TRIGGERS 表
CREATE TABLE IF NOT EXISTS `QRTZ_SIMPROP_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(200) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(200) NOT NULL,
    `STR_PROP_1` VARCHAR(512) NULL,
    `STR_PROP_2` VARCHAR(512) NULL,
    `STR_PROP_3` VARCHAR(512) NULL,
    `INT_PROP_1` INT NULL,
    `INT_PROP_2` INT NULL,
    `LONG_PROP_1` BIGINT NULL,
    `LONG_PROP_2` BIGINT NULL,
    `DEC_PROP_1` DECIMAL(13,4) NULL,
    `DEC_PROP_2` DECIMAL(13,4) NULL,
    `BOOL_PROP_1` TINYINT(1) NULL,
    `BOOL_PROP_2` TINYINT(1) NULL,
    `TIME_ZONE_ID` VARCHAR(80) NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    CONSTRAINT `FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
        REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_BLOB_TRIGGERS 表
CREATE TABLE IF NOT EXISTS `QRTZ_BLOB_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_NAME` VARCHAR(200) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(200) NOT NULL,
    `BLOB_DATA` BLOB NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    CONSTRAINT `FK_QRTZ_BLOB_TRIGGERS_QRTZ_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
        REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_CALENDARS 表
CREATE TABLE IF NOT EXISTS `QRTZ_CALENDARS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `CALENDAR_NAME` VARCHAR(200) NOT NULL,
    `CALENDAR` BLOB NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `CALENDAR_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_PAUSED_TRIGGER_GRPS 表
CREATE TABLE IF NOT EXISTS `QRTZ_PAUSED_TRIGGER_GRPS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_FIRED_TRIGGERS 表
CREATE TABLE IF NOT EXISTS `QRTZ_FIRED_TRIGGERS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `ENTRY_ID` VARCHAR(140) NOT NULL,
    `TRIGGER_NAME` VARCHAR(200) NOT NULL,
    `TRIGGER_GROUP` VARCHAR(200) NOT NULL,
    `INSTANCE_NAME` VARCHAR(200) NOT NULL,
    `FIRED_TIME` BIGINT NOT NULL,
    `SCHED_TIME` BIGINT NOT NULL,
    `PRIORITY` INT NOT NULL,
    `STATE` VARCHAR(16) NOT NULL,
    `JOB_NAME` VARCHAR(200) NULL,
    `JOB_GROUP` VARCHAR(200) NULL,
    `IS_NONCONCURRENT` TINYINT(1) NULL,
    `REQUESTS_RECOVERY` TINYINT(1) NULL,
    PRIMARY KEY (`SCHED_NAME`, `ENTRY_ID`),
    INDEX `IDX_QRTZ_FT_TRIG_INST_NAME` (`SCHED_NAME`, `INSTANCE_NAME`),
    INDEX `IDX_QRTZ_FT_INST_JOB_REQ_RCVRY` (`SCHED_NAME`, `INSTANCE_NAME`, `REQUESTS_RECOVERY`),
    INDEX `IDX_QRTZ_FT_J_G` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
    INDEX `IDX_QRTZ_FT_JG` (`SCHED_NAME`, `JOB_GROUP`),
    INDEX `IDX_QRTZ_FT_T_G` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
    INDEX `IDX_QRTZ_FT_TG` (`SCHED_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_SCHEDULER_STATE 表
CREATE TABLE IF NOT EXISTS `QRTZ_SCHEDULER_STATE` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `INSTANCE_NAME` VARCHAR(200) NOT NULL,
    `LAST_CHECKIN_TIME` BIGINT NOT NULL,
    `CHECKIN_INTERVAL` BIGINT NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `INSTANCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- QRTZ_LOCKS 表
CREATE TABLE IF NOT EXISTS `QRTZ_LOCKS` (
    `SCHED_NAME` VARCHAR(120) NOT NULL,
    `LOCK_NAME` VARCHAR(40) NOT NULL,
    PRIMARY KEY (`SCHED_NAME`, `LOCK_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 4. 初始化默认管理员账户
-- ============================================
-- 注意: 密码为 'admin123' 经过 SHA256 + Salt 加密后的值
-- 程序启动时会自动创建，此处仅作备用
-- INSERT INTO `JOB_USER` (`USERNAME`, `PASSWORD`, `DISPLAY_NAME`, `ROLE`, `IS_ENABLED`)
-- VALUES ('admin', 'YOUR_HASHED_PASSWORD_HERE', '系统管理员', 'Admin', 1);

-- ============================================
-- 5. 操作审计日志表 (JOB_AUDIT_LOG)
-- ============================================
CREATE TABLE IF NOT EXISTS `JOB_AUDIT_LOG` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '日志ID',
    `OPERATOR` VARCHAR(50) NOT NULL COMMENT '操作人用户名',
    `OPERATOR_DISPLAY_NAME` VARCHAR(100) NULL COMMENT '操作人显示名称',
    `ACTION` VARCHAR(100) NOT NULL COMMENT '操作功能',
    `TARGET` VARCHAR(200) NULL COMMENT '操作对象',
    `REMARK` TEXT NULL COMMENT '备注（可存储JSON等较长内容）',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    PRIMARY KEY (`ID`),
    INDEX `IX_AUDIT_LOG_OPERATOR` (`OPERATOR`),
    INDEX `IX_AUDIT_LOG_CREATED_AT` (`CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户操作审计日志表';

-- ============================================
-- 4. 推送配置表 (JOB_NOTIFY_CONFIG_JSON)  ← 实体类 NotifyConfigEntity 对应此表
-- ============================================
CREATE TABLE IF NOT EXISTS `JOB_NOTIFY_CONFIG_JSON` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '配置ID',
    `NAME` VARCHAR(100) NOT NULL COMMENT '配置名称',
    `CHANNEL` VARCHAR(50) NOT NULL DEFAULT 'DingTalk' COMMENT '渠道类型: DingTalk/Feishu/Email',
    `CONFIG` TEXT NOT NULL COMMENT '渠道配置 JSON，钉钉: {"webhookUrl":"...","secret":"..."}',
    `IS_ENABLED` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='推送配置表';

-- ============================================
-- 6. 任务扩展配置表 (JOB_CONFIG)  — 替代 Quartz JobDataMap
-- ============================================
CREATE TABLE IF NOT EXISTS `JOB_CONFIG` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '配置ID',
    `JOB_NAME` VARCHAR(200) NOT NULL COMMENT '任务名称（对应 Quartz JobKey.Name）',
    `JOB_GROUP` VARCHAR(200) NOT NULL COMMENT '任务分组（对应 Quartz JobKey.Group）',
    `DESCRIPTION` VARCHAR(500) NULL COMMENT '任务描述',
    `REQUEST_URL` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '请求 URL',
    `REQUEST_TYPE` INT NOT NULL DEFAULT 2 COMMENT '请求类型（1=GET 2=POST 3=PUT 4=DELETE）',
    `HEADERS` TEXT NULL COMMENT '请求头 JSON',
    `REQUEST_PARAMETERS` TEXT NULL COMMENT '请求参数 JSON',
    `TRIGGER_TYPE` INT NOT NULL DEFAULT 2 COMMENT '触发器类型（1=Cron 2=间隔秒）',
    `CRON` VARCHAR(100) NULL COMMENT 'Cron 表达式',
    `INTERVAL_SECOND` INT NULL COMMENT '间隔秒数',
    `BEGIN_TIME` DATETIME NULL COMMENT '开始时间',
    `END_TIME` DATETIME NULL COMMENT '结束时间（null 表示永不结束）',
    `RUN_TOTAL` INT NULL COMMENT '执行次数上限（0 或 null 表示无限制）',
    `DINGTALK` INT NOT NULL DEFAULT 0 COMMENT '钉钉通知级别（0=不通知 1=仅失败 2=全部）',
    `MAIL_MESSAGE` INT NOT NULL DEFAULT 0 COMMENT '邮件通知级别（0=不通知 1=仅失败 2=全部）',
    `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `IX_JOB_CONFIG_NAME_GROUP` (`JOB_NAME`, `JOB_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务扩展配置表（替代 Quartz JobDataMap）';

-- 完成提示
-- 插入默认用户
INSERT IGNORE INTO `job`.`JOB_USER` (`ID`, `USERNAME`, `PASSWORD`, `DISPLAY_NAME`, `EMAIL`, `IS_ENABLED`, `CREATED_AT`, `LAST_LOGIN_AT`, `ROLE`) VALUES (1, 'admin', 'ZlPvG193VMm7dbjdsBI0C7/XI9iUA2rtuCaSLqO+G98=', '系统管理员', NULL, 1, '2026-01-27 15:02:18', '2026-02-28 10:15:19', 'Admin');
SELECT 'DotJob 数据库初始化完成!' AS Message;
